version: '3.8'

services:
  # 後端應用程式服務
  backend:
    build: .
    container_name: blog-backend
    restart: always
    ports:
      - "8080:8080"
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge
