# fly.toml app configuration file generated for my-blog-mysql on 2024-05-22T17:22:12+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-blog-mysql'
primary_region = 'sin'

[build]
  image = 'mysql:8'

[[vm]]
  size = 'shared-cpu-1x'
  memory_mb = 256

[processes]
  app = """--datadir /data/mysql \
    --default-authentication-plugin mysql_native_password"""

[mounts]
  source = "mysqldata"
  destination = "/data"

[env]
  MYSQL_DATABASE = "some_db"
  MYSQL_USER = "non_root_user"
